Crop Prediction - KNN Classifier

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

df = pd.read_csv('/content/drive/MyDrive/CIP/Final Datasets/1Last_Crop_Recommendation_Dataset.csv')
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

scaler = StandardScaler()
X = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

knn = KNeighborsClassifier(n_neighbors=25, p=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
confusion = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(" Accuracy :", accuracy)
print(" Precision :", precision)
print(" Recall :", recall)
print(" F1-score :", f1)
print(" Confusion matrix :\n", confusion)
print("\n Classification report :\n", report)

 Accuracy : 0.9760869565217392
 Precision : 0.9794523758021486
 Recall : 0.9760869565217392
 F1-score : 0.9760073709600358
 Confusion matrix :
 [[70  0  0  0  0  0  0  0  0  0]
 [ 0 41  0  0  0  0  0  0  0  0]
 [ 0  0 17  0  0  0  0  0  0  0]
 [ 0  0  0 65  0  0  0  0  0  0]
 [ 0  0  0  0 22  0  0  0  0  0]
 [ 0  0  0  0  0 57  0  0  0  0]
 [ 0  0  0  0  0  0 45  0  0  0]
 [ 0  0  0  0  0 10  0 51  0  0]
 [ 0  0  1  0  0  0  0  0 32  0]
 [ 0  0  0  0  0  0  0  0  0 49]]

 Classification report :
               precision    recall  f1-score   support

      Banana       1.00      1.00      1.00        70
 Bengal Gram       1.00      1.00      1.00        41
   Blackgram       0.94      1.00      0.97        17
     Coconut       1.00      1.00      1.00        65
      Coffee       1.00      1.00      1.00        22
      Cotton       0.85      1.00      0.92        57
  Green Gram       1.00      1.00      1.00        45
       Maize       1.00      0.84      0.91        61
    Red Gra